# Day 4

In [1]:
import numpy as np

In [2]:
# Load data from text file
with open('input/day4.txt') as f:
    data_string = f.read()
split_data = data_string.split('\n\n')

# Load numbers from text file (first line) 
nums = np.array(split_data[0].split(',')).astype(int)

print('Number of values = {0}'.format(len(nums)))
print(nums)
print('\n')

# Load boards from text file (subsequent lines)

boards_text = split_data[1:]
boards_text = np.array([board.split('\n') for board in boards_text])

boards_arrays=[]
for i, board in enumerate(boards_text):
    boards_arrays.append(np.array([np.array(line.split(), dtype=int) for line in board]))

print('Number of boards = {0}'.format(len(boards_arrays)))
print(np.array(boards_arrays))

Number of values = 100
[79  9 13 43 53 51 40 47 56 27  0 14 33 60 61 36 72 48 83 42 10 86 41 75
 16 80 15 93 95 45 68 96 84 11 85 63 18 31 35 74 71 91 39 88 55  6 21 12
 58 29 69 37 44 98 89 78 17 64 59 76 54 30 65 82 28 50 32 77 66 24  1 70
 92 23  8 49 38 73 94 26 22 34 97 25 87 19 57  7  2  3 46 67 90 62 20  5
 52 99 81  4]


Number of boards = 100
[[[ 7 42 22 92 60]
  [ 8 88 99 13 12]
  [16 62 86 24 77]
  [20 57 19 67 46]
  [36 83 54 63 82]]

 [[ 7 86 50 78 16]
  [83 45 67 94 58]
  [21 98 99 85 43]
  [71 19 31 22  4]
  [70 51 34 11 61]]

 [[ 4 95 84 51 36]
  [43 40 37 23 85]
  [14 90  8 59 99]
  [ 0 88 68 93 81]
  [25  6 55 19 48]]

 ...

 [[16 27 31 88 86]
  [29 40 65 68 39]
  [15 95 93 69 22]
  [66 48 18 84 11]
  [ 7 51 92 96 99]]

 [[ 0 69 51 12 82]
  [ 4 81 62  2 49]
  [27 66 95 83 70]
  [94 97 99 63 19]
  [87 75 77 73 44]]

 [[82 83 75 95 53]
  [46 47 31 14 64]
  [71 70 11 51 87]
  [ 7 16 63 38 29]
  [89 13 33 41  0]]]


## Part 1 & 2

In [12]:
class Board():
    
    def __init__(self, board_array):
        self.numbers = board_array
        self.remain = set(board_array.flatten())

    @property
    def solved(self) -> bool:
        
        for i in range(5):
            if not any(item in self.remain for item in self.numbers[i, :]):
                return True
            elif not any(item in self.remain for item in self.numbers[:, i]):
                return True
        else:
            return False
        
    @property
    def summed(self) -> int:
        return np.sum(list(self.remain))
    
    def call(self, num):
        board.remain.discard(num)

In [13]:
boards = [Board(board) for board in boards_arrays]

boards_remain = set(list(range(len(boards))))

for num_id, num in enumerate(nums):
    for board in boards:
        board.call(num)
        
    for i, board in enumerate(boards):
        if i in boards_remain:
            if board.solved:
                boards_remain.discard(i)
                print('Board {0} solved on Number {1} ({2})! Answer = {3}'.format(i, num_id, num, board.summed * num))


Board 41 solved on Number 17 (48)! Answer = 44736
Board 20 solved on Number 25 (80)! Answer = 69520
Board 83 solved on Number 28 (95)! Answer = 56620
Board 97 solved on Number 28 (95)! Answer = 83980
Board 15 solved on Number 33 (11)! Answer = 8767
Board 37 solved on Number 35 (63)! Answer = 41643
Board 18 solved on Number 36 (18)! Answer = 15444
Board 57 solved on Number 36 (18)! Answer = 12762
Board 99 solved on Number 37 (31)! Answer = 18073
Board 10 solved on Number 40 (71)! Answer = 55380
Board 7 solved on Number 42 (39)! Answer = 20163
Board 11 solved on Number 42 (39)! Answer = 19227
Board 14 solved on Number 42 (39)! Answer = 25350
Board 29 solved on Number 42 (39)! Answer = 21723
Board 96 solved on Number 45 (6)! Answer = 2688
Board 33 solved on Number 46 (21)! Answer = 8463
Board 43 solved on Number 47 (12)! Answer = 6744
Board 50 solved on Number 47 (12)! Answer = 7968
Board 89 solved on Number 47 (12)! Answer = 5532
Board 3 solved on Number 48 (58)! Answer = 32132
Board 26 